#!bin/node
/*

											|¯\ |\| |¯    | | |¯| |¯  ¯|¯   |\| /¯\ |\/| |¯
											|_/ | |  ¯|   |¯| |_|  ¯|  |    | | |¯| |  | |¯
     _   _   _   _____   _____        _____   _____   _____         _____   _   _   __   _  
    | | | | | | /  ___/ |_   _|      |  ___| /  _  \ |  _  \       |  ___| | | | | |  \ | | 
    | | | | | | | |___    | |        | |__   | | | | | |_| |       | |__   | | | | |   \| | 
 _  | | | | | | \___  \   | |        |  __|  | | | | |  _  /       |  __|  | | | | | |\   | 
| |_| | | |_| |  ___| |   | |        | |     | |_| | | | \ \       | |     | |_| | | | \  | 
\_____/ \_____/ /_____/   |_|        |_|     \_____/ |_|  \_\      |_|     \_____/ |_|  \_| 

*/
// Copyright (c) 2011 Badlee Oshimin
//
//			badlee.oshimin[at]gmail[dot]com
//			github.com/badlee
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//


process.path = process.argv[0];
process.argv.shift();

var sys = require('util'),
	puts = sys.puts,
	ini = require('parser.js'),
	ndns = require('ndns.js'),
	uri = require('url'),
	fs = require('fs');
	console = require('console.js');
	require('_extend.js');
function appProtocol(a,dir){
	var url = uri.parse(a.toLowerCase());
	if(url.protocol ===  "app:")
		a = a.replace("app:/",dir||__dirname);
	return a;
};
var UpdateConfFile = null;
function parseUrl (url) {
    // TODO: Add support for ftp username
    var p = {}, m;
    if (m = url.match(/((\w+):\/\/)?([^\/:]+)?(:([0-9]+))?([^\?#]+)?(\?([^#]+))?(#(.+))?/)) {
        p['scheme'] = m[2]|| null;
        p['host']   = m[3]|| null;
        p['port']   = m[5]|| null;
        p['path']   = m[6]|| null;
        p['args']   = m[8]|| {};
        p['anchor'] = m[10] || null;
        return p;
    }

    return false;
}

var findZone = false;
var fun_dns = [
	0,/*Majeur*/
	1,/*Mineur*/
	10, /*Build*/
	'release' /*state*/
];
;
process.version = process.versions.fun_dns = fun_dns.join(".");
var options = require("options")([
		['p', 'port', ':', "Port d'ecoute du serveur." ],
		['h', 'host', ':', "Port d'ecoute du serveur." ],
		['c', 'conf',    ':', 'Fichier de configuration(hostname).'],
		['s', 'servConf', ':', "Fichier de configuration(serveur)." ],
		['l', 'log' , ':', "Fichier de log"],
		['v', 'version', '',  "Obtention de la version",function(){
			console.log("fun_dns-"+process.versions.fun_dns);
			process.exit();
		}],
		['z',"zone",':',"Obtention d'une zoneWalk",function(zone){
			var walk = function (a_root_servers_net, domain) {
				var resolver = ndns.createClient('udp4');
				puts(domain);
				var req = resolver.request(53, a_root_servers_net);

				req.setHeader({
				id: 1992,
				rd: 1,
				qdcount: 1});
				req.addQuestion (domain, "NSEC", "IN");
				req.send();

				req.on("response", function (res) {
				var rr;
				for (var i = 0; i < res.rr.length; i++) {
					rr = res.rr[i];
					if (rr.typeName == "NSEC") {
					walk(a_root_servers_net, rr.rdata.next_domain_name);
					break;
					}
				}
				});
			}

			require('dns').resolve4(zone, function (err, addrs) {
				if (err){
					console.error("Error", err);
					process.exit();
				};
				if (addrs.length > 0)
				walk(addrs[0], ".");
				process.exit();
			});
		}]
	],{
		script : "fun_dns",
		values : '',
		desc :
"     _   _   _   _____   _____        _____   _____   _____         _____   _   _   __   _\n"+ 
"    | | | | | | /  ___/ |_   _|      |  ___| /  _  \\ |  _  \\       |  ___| | | | | |  \\ | |\n"+ 
"    | | | | | | | |___    | |        | |__   | | | | | |_| |       | |__   | | | | |   \\| |\n"+ 
" _  | | | | | | \\___  \\   | |        |  __|  | | | | |  _  /       |  __|  | | | | | |\\   |\n"+ 
"| |_| | | |_| |  ___| |   | |        | |     | |_| | | | \\ \\       | |     | |_| | | | \\  |\n"+ 
"\\_____/ \\_____/ /_____/   |_|        |_|     \\_____/ |_|  \\_\\      |_|     \\_____/ |_|  \\_|\n"+
"                                      Fun DNS  est un serveur DNS ecrit au dessus de nodejs\n"
	});

var conf;
servConfig = options.servConf || "app://config/serv.ini";
PROXY = [];
NAMES = {};

console.setLog(options.log || "/var/log/fun_dns.log");

if(!findZone){
	var dgram = require('dgram');
	var server = ndns.createServer('udp4');
	var client = ndns.createClient('udp4');

	var CACHE_DNS = {};
	var proxy = function(req,res,name,i){
		if(CACHE_DNS[name]){
			res.setHeader(req.header);
			//CACHE_DNS[name].header = req.header;
			for (var i = 0; i < req.q.length; i++)
				res.addQuestion(req.q[i]);
			
			res.header.qr = CACHE_DNS[name].header.qr;
			res.header.ra = CACHE_DNS[name].header.ra;
			res.header.rd = CACHE_DNS[name].header.rd;

			/* Nombre de reponse */
			res.header.ancount = CACHE_DNS[name].header.ancount;
			/* Nombre de namespace */
			res.header.nscount = CACHE_DNS[name].header.nscount;
			/* Nombre de reponse aditionnel */
			res.header.arcount = CACHE_DNS[name].header.arcount;

			res.rr = CACHE_DNS[name].rr;
			
			res.send();
			console.info("Found",name,"on Cache data");
			return;
		};
		i = i || 0;
		if(!PROXY.length){
			res.send(res);
			console.warn("Not found",name,": Proxies list is empty");
			return;
		};
		
		var c_req = client.request(PROXY[i].port||53, PROXY[i].host);
		
		c_req.on("response", function (c_res) {
			try{
				clearTimeout(this.timeout);
				if((c_res.header.ancount+c_res.header.nscount+c_res.header.arcount)){
					res.send(c_res);
					console.info("Found",name,"on", PROXY[i].host+":"+(PROXY[i].port||53));
					CACHE_DNS[name] = c_res;
					setTimeout((function(name){
						CACHE_DNS[name]=false;
					}).bind(null,name),1000*60*60);
				}else{
					console.info("\tNot Found", name ," on this DNS : ", PROXY[i].host+":"+(PROXY[i].port||53));
					if(++i<PROXY.length){
						proxy(req,res,name,i);
					}else{
						res.send(c_res);
						console.warn("Not found",name,"on all proxies");
					}
				}
			}catch(e){};
		});
		c_req.send(req);
		
		c_req.timeout  = setTimeout((function(name){
			console.info("\tRequest",name,"Timeout on : ", PROXY[i].host+":"+(PROXY[i].port||53));
			//try{this.socket.close();}catch(e){};
			if(++i<PROXY.length){
				proxy(req,res,name,i);
			}else{
				res.send(res);
				console.warn("Not found",name,"on all proxies");
			}
		}).bind(c_req,name),1500);
		console.info("\tTry DNS ", PROXY[i].host+":"+(PROXY[i].port||53));
	};
	var getRecords = function(data,name){
		var ret = {
			REP : [],
			NS  : [],
			ADD : []
		};
		var i=0;
		var j,k=0;
		for(i in data){
			j = String(data[i]).replace(/{name}/g,name);
			switch(i.toLowerCase()){
				case 'ip':
					/* adresse IP */
					data[i] = data[i] instanceof Array ? data[i] : [data[i]];
					data[i].rotate(1);
					for(var x=0; x< data[i].length;x++)
						ret.REP.push([name,77, "IN", "A", data[i][x]]);
					break;
				case 'description':
					ret.REP.push([name, 86400, "IN", "TXT", data[i]]);
					break;
				case 'autority':
					data[i] = String(j).split(',').slice(0,2);
					data[i] = data[i].length ==1 ? data[i].concat(data[i]) : data[i]; 
					ret.REP.push([name, 86400, "IN", "SOA"].concat(data[i]).concat([UpdateConfFile,1800, 900, 604800, 86400]));
					break;
				case 'mail':
					data[i] = data[i] instanceof Array ? data[i] : [data[i]];
					var k = 0;
					for(j = 0;j< data[i].length;j++){
						data[i].name = data[i][j].name? data[i].name.replace(/{name}/g,name) : "mail."+name;
						ret.REP.push([name, 86400, "IN", "MX", data[i][j].priority || (++k)*10, data[i][j].name]);
						if(data[i][j].ip){
							data[i][j].ip = data[i][j].ip instanceof Array ? data[i][j].ip : [data[i][j].ip];
							data[i][j].ip.rotate(1);
							for(var x=0; x< data[i][j].ip.length;x++)
								ret.ADD.push([data[i][j].name, 77, "IN", "A", data[i][j].ip[x]]);
						}
					}
					break;
				case 'nameserver':
					for(j = 0;j< data[i].length;j++){
						data[i][j].name = data[i][j].name? data[i][j].name.replace(/{name}/g,name) : "ns"+(++k++)+"."+name;
						ret.NS.push([name, 86400, "IN", "NS" , data[i][j].name]);
						if(data[i][j].ip){
							data[i][j].ip = data[i][j].ip instanceof Array ? data[i][j].ip : [data[i][j].ip];
							data[i][j].ip.rotate(1);
							for(var x=0; x< data[i][j].ip.length;x++)
								ret.ADD.push([data[i][j].name, 77, "IN", "A", data[i][j].ip[x]]);
						};
					}
					break;
				
				case 'alias':
					for(j = 0;j< data[i].length;j++){
						data[i][j].name = data[i][j].name? data[i][j].name.replace(/{name}/g,name) : "ns"+(++k++)+"."+name;
						ret.REP.push([name, 86400, "IN", "CNAME" , data[i][j].name]);
						if(data[i][j].ip){
							data[i][j].ip = data[i][j].ip instanceof Array ? data[i][j].ip : [data[i][j].ip];
							data[i][j].ip.rotate(1);
							for(var x=0; x< data[i][j].ip.length;x++)
								ret.REP.push([data[i][j].name, 77, "IN", "A", data[i][j].ip[x]]);
						};
					}
					break;
			}
		}
		return ret;
	};
	server.on("request", function(req, res) {
		if (req.q.length > 0) {
			var name = req.q[0].name;
			if (name == ".")
				name = "";
			/* Test le nom */
			//find info dns here
			var rec;
			if(NAMES && NAMES[name]){
			    rec = getRecords(NAMES[name],name);
			}else{
				if(NAMES){
			   		for(i in NAMES){
				   		if(i.search(/\!/) != 0) continue;	
				   		t = i
				   			.replace("!","")
                            .replace(/\./g,"\\.")
                            .replace("*",".*")
                            .replace("%w","[a-zA-Z0-9_]+")
                            .replace("%d","[0-9]+")
                            .replace("%h","[a-fA-F0-9]+");
			   			t = new RegExp("^"+t+"$");
			   			if(t.test(name)){
			   				console.info("Found",t,"in",name);
			   				rec = getRecords(NAMES[i],name);
			   			}
			   			t = '';
			   		}
			   	}
			}
			/* ** */
			if(!rec){
				console.warn("Not found",name,"on this server, try to use proxy");
				proxy(req,res,name);
				return;
			}
			
			res.setHeader(req.header);	
			for (var i = 0; i < req.q.length; i++)
				res.addQuestion(req.q[i]);
			
			res.header.qr = 1;
			res.header.ra = 1;
			res.header.rd = 0;
			
			/* Nombre de reponse */
			res.header.ancount = rec.REP.length;
			/* Nombre de namespace */
			res.header.nscount = rec.NS.length;
			/* Nombre de reponse aditionnel */
			res.header.arcount = rec.ADD.length;
			/* ajout des reponses */
			var j = 1;
			for(var i=0;i<rec.REP.length;i++){
				res.addRR.apply(res,rec.REP[i]);
			}
			
			/* ajout des NS */
			for(var i=0;i<rec.NS.length;i++){
				res.addRR.apply(res,rec.NS[i]);
			}
			
			/* ajout des ADD */
			for(var i=0;i<rec.ADD.length;i++){
				res.addRR.apply(res,rec.ADD[i]);
			}
			
		}else{
			res.setHeader(req.header);	
			for (var i = 0; i < req.q.length; i++)
				res.addQuestion(req.q[i]);
		};
		res.send();
	});
	var loadConf = function(conf){
		try{
			console.info("LOAD Config Domain name");
			conf = JSON.parse(conf);
			NAMES = conf;
			console.info("\tConfig loaded");
		}catch(e){
			console.error("\tError on decode Config",e.stack,"#",conf,"#");
		}
		console.info("End LOAD Config");
	}
	/* function for load server */
	var loadDataServer = function(serv,proxyOnly){
		serv.nameserver = serv.nameserver.length ? serv.nameserver[0] : [];
		  
		  PROXY =  [];
		  console.info("LOAD DNS Server");
		  for(i in serv.nameserver){
		  	if(typeof serv.nameserver[i] == "string"){
		  		console.info("\tADD DNS Server",serv.nameserver[i]);
			  	PROXY.push(parseUrl(String(serv.nameserver[i])));
			}
		  }
		  if(PROXY.length)
		  	console.info(PROXY.length+" DNS Server added");
		  else
		  	console.info("No DNS Server to add");
		  if(Boolean(proxyOnly))return;
		  /*define config page*/
		  conf = options.conf || serv.conf || "app://config/conf.json";
		  conf = appProtocol(conf);
		  fs.readFile(conf, function (err, data) {
			  if (err){
			  	console.error('Fatal Error : Can\'t read Config at ' + conf );
			  	process.exit(1);
			  };
			
			  UpdateConfFile = fs.statSync(conf).mtime.format("Ymd11");
			  loadConf(String(data));
			  fs.watchFile(conf, function (curr, prev) {
					fs.readFile(conf, function (err, data) {
						if (err){
						  	console.error('Can\'t read Config at ' + conf );
						  	return;
						  };
						loadConf(String(data));
					});
				});
				
			  serv = {
				host : options.host || serv.host || null,
				port : options.port || serv.port || 53
			  };
			  serv.port = Number(serv.port);
			  if(serv.host && serv.host != 0){
				  server.bind(serv.port, serv.host);
				  console.info('Started server on ' + serv.host + ':' + serv.port);
			  }else{
			  	server.bind(serv.port);
			  	console.info('Started server on *:' + serv.port);
			  }
			});
		  /* ** */
	}
	/* ** */
	/* function pour */
	/* ** */
	servConfig = appProtocol(servConfig);
	fs.readFile(servConfig, function (err, data) {
	  if (err){
	  	console.error('Fatal Error : Can\'t read Config server at ' + servConfig );
	  	process.exit(1);
	  };
	  loadDataServer(ini.parseString(String(data),true));
	  fs.watchFile(servConfig, function (curr, prev) {
			fs.readFile(servConfig, function (err, data) {
				if (err){
				  	console.error('Can\'t read Config server at ' + servConfig );
				  	return;
				  };
				loadDataServer(ini.parseString(String(data),true),true);
			});
		});
	});
};

process.on('uncaughtException', function (err) {
  console.error("Erreur",":", err.code || err.stack || err);
  if(err.code){
  	switch(err.code){
  		case 'EADDRNOTAVAIL':
  			console.error("\tL'adresse n'est pas disponible!");
  			break;
  		case 'EADDRINUSE':
  			console.error("\tLe port est deja utilise!");
  			break;
  		case 'EACCES':
  			console.error("\tVerifier vos droits!");
  			break;
  	}
  	process.exit();
  };
});
